### ISSUE TITLE
Border radius support

### ISSUE THREAD

**Issue by johanolandero** [wuxudong/react-native-charts-wrapper#110]
Greetings.

Trying to look over the docs and source but can't find anything fulfilling my need of border radius on bars in a bar chart.

Is it possible to achieve this?

**Comment by wuxudong** [comment]
I don't get it. can you attach a pic for detail?

**Comment by johanolandero** [comment]
Something like this with rounded corners.

![border radius github](https://user-images.githubusercontent.com/23318359/33220184-96a207d2-d146-11e7-913c-88199ce3ffd0.png)

**Comment by mantas-janulionis** [comment]
@johanolandero it is not possible to achieve this out-of-the-box. The underlying native chart implementations for iOS and android do not support this functionality. It took me some effort to fork these three libraries, implement custom path drawing and pass the props.

I think this issue should be addressed to the native libraries rather than wrapper library

**Comment by c0d3blooded** [comment]
Looks like this is a work in progress at least on the iOS Charts side.
https://github.com/danielgindi/Charts/pull/1917

**Comment by wuxudong** [comment]
Won't be implemented until native libraries support it.

**Comment by zxy198717** [comment]
@wuxudong seems native has supported it.

**Comment by asadqazi** [comment]
is it achievable now? radius is supported now?

**Comment by Eramirez06** [comment]
any news?
