### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.bool')

### ISSUE THREAD

**Issue by aditya-simplecrm** [wuxudong/react-native-charts-wrapper#127]
After installing this package getting error 
undefined is not an object (evaluating '_react.PropTypes.bool')
unknown
AxisIface.js:5:21

react-native-cli: 2.0.1
react-native: 0.46.4

**Comment by GermanMontejo** [comment]
I'm also having the same issue. What went wrong with this library? When I tried it a like a few weeks ago on a test project, it was working. Now it's showing the problem above, when I try to run it via react-native run-android

**Comment by kssujithcj** [comment]
Hi @aditya-simplecrm, @GermanMontejo,
Even I have the same issue.
I can run example project but not new project with react native version 0.49.3

@wuxudong,
I followed every step provided in the readme for iOS but in the last part where it says set no for legacy swift. I can't find that option in Xcode 9.0, however, the swift language version being used is 3.2
Please update if you figure out something.

**Comment by kssujithcj** [comment]
I managed to get it work, it is because this library is using the old version of react.
You just need to change the import statement of propTypes.
Change import of PropTypes wherever it shows the error,

import PropTypes from 'prop-types';

source: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html

**Comment by aditya-simplecrm** [comment]
@kssujithcj I also tried the same earlier but I was getting error 
undefined is not an object (evaluating '_react.PropTypes.string')
unknown
AxisIface.js:5:21

**Comment by kssujithcj** [comment]
double click on that it will open that file, just keep changing import statement till all the import statements are resolved.

**Comment by kssujithcj** [comment]
@wuxudong,
I had another issue wherein swift libraries were not linked to project since default adding files will create just a folder and not group in the project. So even though I was able to run the project, charts were not being displayed.

So steps to follow was while adding files to project in pop-up select options at the bottom and select the radio button "Create groups" instead of "Create folder references".

Maybe this is naive, I am new to iOS framework. I was stuck for a while to create a new project.
Please add this point in the readme it might help others.
Thank you.

**Comment by kssujithcj** [comment]
@wuxudong,
I also see this warning for all ChartManagers,

Module RNLineChartManager requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

Maybe this library will break in later versions of react native. Please do consider this for your next release.

**Comment by aditya-simplecrm** [comment]
Any fixes?

**Comment by kssujithcj** [comment]
@aditya-simplecrm,
I am already using this library in my project. Just replace the import statements with

import PropTypes from 'prop-types';

That should resolve the issue.

**Comment by kyle-ssg** [comment]
Looks like this was fixed as part of a recent pull request

**Comment by kyle-ssg** [comment]
https://github.com/wuxudong/react-native-charts-wrapper/pull/140

**Comment by wuxudong** [comment]
@kssujithcj Thanks for your remind. It is already fixed in the latest version. Thanks for all.

**Comment by DavitVosk** [comment]
Hi guys. I have the same problem with react-native-chart. Could you please help to solve the problem

**Comment by waqaramjad** [comment]
still facing same issue
