### ISSUE TITLE
Anyone Having Trouble running on IOS? 

### ISSUE THREAD

**Issue by sourceship13** [wuxudong/react-native-charts-wrapper#196]
I am having issues building to IOS. I followed the steps in the detailed guide: [https://www.evernote.com/shard/s304/sh/5d501d94-a8e0-4309-9866-e2026356a29d/130a7aa8b84d73a6] but I keep on getting this error message when I run `react-native run-ios `: 

```
Installing build/Build/Products/Debug-iphonesimulator/RaptorrMobile.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RaptorrMobile.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

I'm not sure what I may be doing wrong. I downloaded and have been using Xcode 8 since I get a Message when using Xcode 9.2 that says: 
```

Unsupported Swift Version
The target "" contains source code develiped with Swift 2.x Xcode 9 does not support building or migrating Swift 2.x targets 
Use Xcode 8.x to migrate the code to Swift 3. 
```

Idk if this is something I am doing wrong or if other have this issue as well? My pod file is exactly what is in the guide. When I first created a swift file in the Xcode project nothing popped up about creating a Bridging Header file so I created a header file myself and added the imports there manually. I set the project setting properly in the Xcode Setting as well by following the instructions in the guide posted. I made sure to create groups like listed in the guide. 
Also I created this project by running `create-react-native-app `

If anyone else has this issue or has a fix please let me know, Im wokring on trying to get this fixed, I just have limited exp with Swift and React Native projects. 

Thanks in Advance,

**Comment by wuxudong** [comment]
I think Xcode is asking you to migrate swift to 3.x using Xcode 8.x, then switch back to Xcode 9.x.

Swift 3.x is necessary for this lib.

**Comment by sourceship13** [comment]
Hi, 

I used Xcode 8 to open and migrate this project to Swift 3. Then I made sure the other configurations were made as noted in the ios Setup Guide. All of which worked successfully. 

I am still getting a built error though when I run the `react-native run-ios` command. 
This is the error: 

** BUILD FAILED **


The following build commands failed:

        CompileC /Users/aj/AlphaProjects/RaptorrMobileReact/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/signalhandler.o /Users/aj/AlphaProjects/RaptorrMobileReact/node_modules/react-native/third-party/glog-0.3.4/src/signalhandler.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/aj/AlphaProjects/RaptorrMobileReact/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/raw_logging.o /Users/aj/AlphaProjects/RaptorrMobileReact/node_modules/react-native/third-party/glog-0.3.4/src/raw_logging.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

Installing build/Build/Products/Debug-iphonesimulator/RaptorrMobile.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RaptorrMobile.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist



Have you experience this error before? I'm not sure how to resolve this error?

**Comment by wuxudong** [comment]
Can you run example successfully?

and I notice in example project, the swift language settings is 3.2

<img width="525" alt="screen shot 2018-02-06 at 2 21 14 am" src="https://user-images.githubusercontent.com/1391101/35821616-93679dfc-0ae4-11e8-8a6a-5f310538f905.png">

**Comment by sourceship13** [comment]
The example project did successfully build. But it only showed a white screen when the app loaded. I am still playing with it to get it to show the app properly. 

I'm not sure why my app is not building for ios, but I am still trying to see why. it fails when its building with that CFBundleIdentifier Does not Exist error.

**Comment by sourceship13** [comment]
Actually I just ran the example project again, it runs fine. I'm still looking into the CFBundleIndentifier Issue.  My Project swift version is also at 3.2.

**Comment by sourceship13** [comment]
The example project is working now: no white screen, runs fully. Its just my build that keeps on failing. 
I see other people with the same problem, I'm trying different things to try to get it to work. 

Here some threads with similar problems, so far their solutions do not work for me; ill keep updating this thread until I find the fix, in case someone else needs it. 

https://github.com/facebook/react-native/issues/10401
https://github.com/facebook/react-native/issues/11265#issuecomment-265663635
https://github.com/facebook/react-native/issues/14423

None of those helped me but I'll update when I find a fix. It keeps on failing on the building process and gives me the error from my first post in this thread.

**Comment by wuxudong** [comment]
Good luck.

**Comment by sourceship13** [comment]
Okay it looks like I got everything working. 
If you all are getting an error in Xcode talking about a Config.h is missing and getting the same build error as me when running `react-native run-ios` as me then try this from this thread: [https://github.com/facebook/react-native/issues/14382#issuecomment-313163119](url)

This fixed my problem and after I ran the project from Xcode it was able to build and deploy to my iPhone. 

I hope this can help anyone else that has this similar problem in the future.

**Comment by dbnex14** [comment]
This issue is still present and none of the solution in [https://github.com/facebook/react-native/issues/14423](https://github.com/facebook/react-native/issues/14423) resolved it

None of the suggestions above are working. I am still having same error and @srijak 's suggestion how to recreate this by simply creating new project is incorrect. If I create brand new project, I can run it in both IOS and Android with no issue.
But following few suggestions how to add GoogleMaps, all result in this error so following for example this link will land you with that error
https://medium.com/quick-code/react-native-location-tracking-14ab2c9e2db8 but again every single attempt to add Google Maps resulted in this issue. Interestingly, it works fine on Android, it is only iOS that is the problem.

react-native-cli 2.0.1
react-native 0.55.4
macOS El Capitan, MacBookPro
npm 5.5.1
node -v 8.9.1
watchman 4.9.0

I tried all suggestions above and while the issue is easily reproducible, the error still exists. Also, number of other tickets were created and closed claiming this one or some other solve the issue, yet issue is still present

As explained earlier, I tried number of online articles to add Google Maps/Arbnb Maps (react-native-maps) when I started seeing this issue only in IOS. Some of these articles are below for people to try, you should get this error if you try, for example, both of these link if followed will produce this error. I also tries numerous suggestions here or elsewhere, none of which worked.
https://www.codementor.io/uokesita/integrate-airbnb-google-maps-in-a-react-native-app-dxjp5p5ed
https://medium.com/quick-code/react-native-location-tracking-14ab2c9e2db8

** BUILD FAILED **

The following build commands failed:
	CompileC build/Build/Intermediates.noindex/locationTracking.build/Debug-iphonesimulator/locationTracking.build/Objects-normal/x86_64/AppDelegate.o locationTracking/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/locationTracking.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/locationTracking.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by wuxudong** [comment]
Reopen it if necessary

**Comment by JeremyBradshaw7** [comment]
Having similar issues as reported, until this library makes setup easier for iOS I'm going to have to look for something else, shame as it looked like it provided everything we needed.
