### ISSUE TITLE
When the chart linkage, the chart slide is slow

### ISSUE THREAD

**Issue by huanglaoju** [wuxudong/react-native-charts-wrapper#207]
![image](https://user-images.githubusercontent.com/19677313/35839665-97b26d54-0b2c-11e8-87fd-e94ac0751ade.png)
![image](https://user-images.githubusercontent.com/19677313/35839686-b5912a7c-0b2c-11e8-8c1f-951219b59504.png)
This problem is wrong code or performance problems? Can you help me? I am puzzled for a long time

**Comment by wuxudong** [comment]
When dragging the chart, the chartTranslated is trigger so frequently (maybe 100 times per second?) that affect app performance a lot.

One possible solution is drop  some middle event, but it will make linkage not quite smooth,

Or another solution is using some better performance operation, maybe set viewport other than zoom.  

I am not sure if react-native also affect performance because setState call is so frequent (Just like useNativeDriver in animation affect performance a lot).

**Comment by wuxudong** [comment]
Two combined charts in screenshot?

**Comment by huanglaoju** [comment]
@wuxudong two combined chart in sync screenshot ,How to set the zoom outside of the viewport?
