### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNPieChart" was not found in the UIManager.

### ISSUE THREAD

**Issue by CoderGMLee** [wuxudong/react-native-charts-wrapper#382]
![simulator screen shot - iphone x - 2018-08-31 at 16 33 05](https://user-images.githubusercontent.com/13034570/44902137-bec41f80-ad3b-11e8-8726-4d1ad4ab91f8.png)

when I tap PieChart cell, it crash，how should i do?

**Comment by wuxudong** [comment]
Run it in Example.

**Comment by wuxudong** [comment]
It works fine in my computer, my local code is consistent with master branch.

**Comment by NSLS** [comment]
+1 

Neither Example project or installing following the instruction works for the latest version.

Example works with 0.4.3 though, so this might be the problem with the latest release or it's installation method via cocoapods

**Comment by wuxudong** [comment]
It seems 

```
 "react-native-charts-wrapper": "file:../",
```

in package.json doesn't work well with `npm install`  .

After `npm install`, It will create an alias in node_modules.

<img width="684" alt="screen shot 2018-09-01 at 12 00 16 pm" src="https://user-images.githubusercontent.com/1391101/44942177-aa852e80-adde-11e8-91dd-0ee900941c47.png">

Then, when you run `pod install` under ios directory.

<img width="278" alt="screen shot 2018-09-01 at 12 01 45 pm" src="https://user-images.githubusercontent.com/1391101/44942186-f041f700-adde-11e8-8846-30157a6d23c0.png">

Notice RNCharts directory is blank!

That is the reason why example fails.

After I change 'npm install' to 'yarn install', every thing works fine.

yarn will copy files to node_modules.

<img width="655" alt="screen shot 2018-09-01 at 12 05 07 pm" src="https://user-images.githubusercontent.com/1391101/44942202-4e6eda00-addf-11e8-899a-76514b25012f.png">

<img width="280" alt="screen shot 2018-09-01 at 12 06 11 pm" src="https://user-images.githubusercontent.com/1391101/44942209-752d1080-addf-11e8-83da-a254c8a31d5c.png">

**Comment by wublack** [comment]
我也有相同的问题，在iOS设备上（Android端没有问题），按照你的安装指南一步步来，都没有成功，一直报这个错，唯一的差别的是我的xcode版本是9.1,其他我都是按照你的readme文件来。一个星期了。头大。

**Comment by Jeijie** [comment]
same issue any update ?

**Comment by devonhuangcodes** [comment]
I’m not getting exactly the same behaviour as wuxudong but as he mentioned there’s probably something going on with npm. I had the same issue and what I did to resolve it was to use yarn in my project instead of npm. I also linked the subproject using the manual method instead of cocoapods since I was running into a lot of issues with that as well. Here’s a modified step-by-step process of the tutorial from https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md

1. react-native init demo
2. cd demo
3. yarn add react-native-charts-wrapper
4. yarn add @babel/runtime
5. update your App.js
6. add postinstall in package.json
7. rm -rf node_modules && rm package-lock.json && yarn install
8. link subproject (**USE MANUAL SETUP**)

**Comment by zry754331875** [comment]
l also use yarn instead of npm,but it still.

**Comment by zry754331875** [comment]
l try manual setup can fix this problem.

**Comment by HasanElfalt** [comment]
> l try manual setup can fix this problem.

how do you setup this library manually?
