### ISSUE TITLE
StackedBar marker set digits=2, ios not work

### ISSUE THREAD

**Issue by s349856186** [wuxudong/react-native-charts-wrapper#454]
![image](https://user-images.githubusercontent.com/2498958/49326089-bf14c680-f587-11e8-9875-9e3b3c6c192e.png)

I want to digits=2, android is ok, but ios not work.

        marker={{
                            enabled: true,
                            markerColor: processColor('transparent'),
                            textColor: processColor('white'),
                            markerFontSize: 14,
                            valueFormatter: '####.##',
                            digits: 2,
                        }}
### Specifications
  - Version:"react-native-charts-wrapper": "^0.5.0",
  - Platform:"0.51.0",
  - Subsystem: IOS

**Comment by s349856186** [comment]
@wuxudong Can you help me?Thanks.

**Comment by s349856186** [comment]
> I would like to ask you, after integrating this component into ios, can you still open the developer menu of the simulator in debugging? I can't open the developer menu in the ios emulator.

command+D
I think it should not be the reason for this library. @vitozyf

**Comment by vitozyf** [comment]
It's true that after I integrated in the project, the developer menu didn't open in the ios emulator. In order to exclude other factors, I created an empty project, running ios can open the developer menu, again after the integration of the library did not open the developer menu.

By the way, I use cocoapods for automatic integration

"react": "16.6.1",
"react-native": "0.57.7",
"react-native-charts-wrapper": "^0.5.0"

"swift": "4.2"
"xcode": "10.1"

I wrote a demo and only integrated this library. Please help me have a look. Thank you very much.
https://github.com/vitozyf/chartDemo

**Comment by s349856186** [comment]
@vitozyf Sorry, i not used 0.57, you can try integrated other project test. And you should create a new issue, my issue not resolved yet

**Comment by vitozyf** [comment]
Ok, thank you all the same.
Please tell me your version and I will try again.

“react”：“”，
“react-native”：“”，
“react-native-charts-wrapper”：“”
“swift”：“” 
“xcode”：“”

**Comment by s349856186** [comment]
"react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-charts-wrapper": "^0.5.0",
    "swift": "3"
    "xcode": "10.1"

**Comment by s349856186** [comment]
I don't know what the reason is., 
But I need 2 decimals, so i modify BarChartDataEntry.swift-->calcSum
        sum=(sum * 100.0).rounded()/100.0
        return sum

**Comment by wuxudong** [comment]
In your picture ,  it looks like value label, not marker. so marker configuration won't work.
