### ISSUE TITLE
CompileSwift failed when upgrade Xcode 11 

### ISSUE THREAD

**Issue by longhust** [wuxudong/react-native-charts-wrapper#604]
### Issue
I upgrade Xcode 11 and have issue about CompileSwift failed. Do you have any solution to this problem?

### Specifications

  - react-native: 0.60.5
  - Platform: IOS 13, Xcode 11

**Comment by Dddingnan** [comment]
+1, please.

**Comment by wuxudong** [comment]
A new version is published, and the installation tutorial is updated, give it a try.

**Comment by Dddingnan** [comment]
It's work perfectly on both iOS and Android.
Thanks !!


react-native info:

System:
    OS: macOS 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.88 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by zmnv** [comment]
@wuxudong 

After implements [Sentry](https://docs.sentry.io/platforms/react-native/#integrating-the-sdk) in project:
1. `react-native run-ios` build failed by swift errors
2. Build from XCode – everything okay, build success!

```
<path-to-project>/ios/build/<app-name>/Build/Products/Debug-iphonesimulator/Charts/Charts.modulemap:1:8: note: previously defined here
module Charts {
       ^
<unknown>:0: error: could not build Objective-C module 'SwiftShims'
```
```
CompileSwift normal x86_64 <path-to-project>/ios/Pods/Charts/Source/Charts/Data/Implementations/Standard/ScatterChartDataSet.swift (in target 'Charts' from project 'Pods')...
```

```
<path-to-project>/ios/Pods/Headers/Public/Charts/Charts.modulemap:1:8: error: redefinition of module 'Charts'
module Charts {
       ^
... so many times the same text
```

and after:

```
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 <path-to-project>/ios/Pods/Charts/Source/Charts/Jobs/AnimatedMoveViewJob.swift
	CompileSwift normal x86_64 <path-to-project>/ios/Pods/Charts/Source/Charts/Jobs/AnimatedViewPortJob.swift
	CompileSwift normal x86_64 <path-to-project>/ios/Pods/Charts/Source/Charts/Jobs/AnimatedZoomViewJob.swift

.... other 99 files

	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(137 failures)
```

**Comment by zmnv** [comment]
upd: I deleted DerivedData from `Library/Developer/Xcode` and  now in XCode I can see:

```
18 duplicate symbols for architecture x86_64
```

```
duplicate symbol '_OBJC_CLASS_$_RNBarChartManager' in:
    ~/Library/Developer/Xcode/DerivedData/enapter-bsgztsmusqnrgrgyngrclwcgalww/Build/Intermediates.noindex/enapter.build/Release-iphonesimulator/enapter.build/Objects-normal/x86_64/RNBarChartManager.o

```

and same 17 errors

**Comment by davidmarinangeli** [comment]
Same here @zmnv with [both automatic and manual installation](https://github.com/wuxudong/react-native-charts-wrapper/tree/master/installation_guide). I tried with a fresh project and it does the same. With a fresh project and manual installation, it seems to miss some React files.

XCode 11
RN 0.61.3

Unfortunately all the libraries work but this. Has someone tried and found a proper workaround?

![Screenshot 2019-10-31 at 16 08 24](https://user-images.githubusercontent.com/19487461/67959269-be9e0900-fbf8-11e9-8105-3a4cd4e82758.png)

**Comment by zmnv** [comment]
@davidmarinangeli and other who has same problem.

I fixed that by don't following installation guide :)

**React Native 0.61.2**

### For new a project

```
> yarn add @babel/runtime -D
> yarn add react-native-charts-wrapper
```

**iOS**
I just added `RNCharts` before `use_native_modules!` in `Podfile`.
Don't copy anything in XCode like that said in guide.

```
// Podfile

pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
```

```
> cd ios
> rm -rf Pods
> pod install
```

**Android**
Nothing to do because of autolinking. New version of React Native (0.60+) has:

```java
// MainApplication.java
// ...
List<ReactPackage> packages = new PackageList(this).getPackages();
// ...
```

---

### For existing project with `react-native-charts-wrapper` like 0.5.5

**Main idea**
1. Remove charts dependencies from project
2. Try to build project without charts
3. Install charts only automatically (for iOS only what to do is create new bridge header)

### Steps

1. Update `@babel/runtime` to 7.6.3+
2. 

```
yarn remove react-native-charts-wrappe
```

**iOS**

3. Remove `SwiftyJSON` and `Charts` from `Podfile` (they already has in `RNCharts`)

Then:

```
> cd ios
> rm -rf Pods
```

4. Remove all `RNCharts` folder from your XCode project with *bridge header* (make sure you have not code for other modules in header) 

<img src="https://user-images.githubusercontent.com/25253501/67979291-0179d400-fc2d-11e9-9954-de7d12c80b4c.png" height="200" />

5. Go to **Build Settings**, find path to header file and delete it.

6. Go to **Build Phases > Compile Sources** and delete all charts files.

7. Return to **Build Settings**, try to find any information about 'chart'. I don't remember, do you need to delete anything there. Think about it by yourself.

8. **Product > Clean Build Folder**

9. Do that step from guide (create new bridge header)

<img src="https://user-images.githubusercontent.com/25253501/67979733-eeb3cf00-fc2d-11e9-8c29-5a58c70fea16.png" width="300" />

I called my bridge like \<projectName\>-Bridging-Header. That step creates 2 files:
* \<projectName\>-Bridging-Header.swift
* \<projectName\>-Bridging-Header.h

Don't write to they anything.

10. 
```
> cd ios
> pod install
```

11. You can remove charts from JS files or just comment code about it. **Just try to build project without charts.**

If you get build failed then you should scan your project in XCode, find anything about charts and delete it. Be careful.

If you get build success you can install charts again.

12. Add before `use_native_modules!` in `Podfile`
```
pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
```

13. 

```
> yarn add react-native-charts-wrapper
> cd ios
> pod install
```

14. Uncomment your charts code in JS files and try to build.

My current \<projectName\>.xcworkspace in XCode:
<img src="https://user-images.githubusercontent.com/25253501/67980830-43f0e000-fc30-11e9-8f21-5f70c7109267.png" width="400" />

**Android**

1. Remove all information about charts. Imports, defines and etc. Look at the guide and do the inverse :)

2. I have no any word about charts in my android files.

3. Reinstall package with yarn or npm.

---------

# New in charts 0.5.7

**If you use gradients**
Now prop `fillAlpha` is required for dataset config! There is no information about that in changelog or readme.

**Comment by davidmarinangeli** [comment]
@zmnv thanks for the well-written reply! I will try your solution as soon as I will fix a problem with another library 😛

**Comment by SimonPotier** [comment]
I had trouble with the installation, @zmnv steps helped me to figure it out. 
For IOS just generate the pods, I also had to create the .swift file to create the header in order to make it work.  
For those who are struggling to build for Android, on the recent react-native versions you just have to add the following line on the `allprojects` -> `repositories` hash in `build.gradle` file:
```
maven { 
     url "https://jitpack.io"
}
``` 
Hope it can help you gain time.
