### ISSUE TITLE
How can i enhance the library through xcode since there is no workspace i can work on in ios folder?

### ISSUE THREAD

**Issue by angelos3lex** [wuxudong/react-native-charts-wrapper#677]
Hey @wuxudong . I made a fork of the library trying to add some new functionality that was missing and i needed. I'm going to open a pr after i finish it.
So, to test my changes, i made a new test-app, that uses my fork as reference, and every change i make to my fork i can live test it on my test-app.
To change the code in android bridge, i can open the android project through android studio, so i can have autocomplete by the ide with all the great help that it comes from it. And i achieved what i needed in android.
Being new to swift and ios programming, i don't know how can the same be achieved for the ios bridge? All i can see in the ios folder, are some .m and .h files, but no workspace that i can open and work on, on the same way as in android. So i can't get the benefits of the xcode ide, like proposing me of functions available in the charts classes etc.
How can i achieve this? What's your way of testing new changes to the ios bridge?

**Comment by jacruzca** [comment]
I needed the same a couple weeks ago. What I ended up doing was using the Example app included in the code and tested my library changes against it. You'll see that it has a reference to `file:..` in package.json (https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/package.json#L18)

To make changes to the library I used VSCode since I could never open it in XCode. Changes to the Example app were made in XCode.

After any change you make in the library, you can see them working in the Example app just by running it in Xcode.

When all the changes were ready in the library and tested in the Example app then I pushed the library code to a private repository and referenced it in the `package.json` of my app.

PS: I wanted to achieve the same, change the library code and see the changes directly in my app. I couldn't do that.

Hope it helps

**Comment by angelos3lex** [comment]
What I finally did was to fork the lib and use it on a new project... Then I could open in xcode the fork and use the autocomplete/suggestion features that xcode has. Maybe not the quickest solution, but it satisfied my needs
