### ISSUE TITLE
ios support long press gesture?

### ISSUE THREAD

**Issue by L-Jovi** [wuxudong/react-native-charts-wrapper#7]
thanks for your smart project.

I want to add callback which could pass x and y axis data in iOS side like android gesture of **LongPressed** effect, but I don't know which property could implements it.

please notice [this link](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/listener/OnChartGestureListener.java#L33).
`void onChartLongPressed(MotionEvent me);`

thanks for your time.

regards :)

**Comment by wuxudong** [comment]
there is already ValueSelectionCallback,   
does it meet you request?

**Comment by L-Jovi** [comment]
@wuxudong  thanks, I find onSelect in your example.

and I migrate to integrate your project in swift 3.0 environment but encounter below error as image show.

![image](https://cloud.githubusercontent.com/assets/7262199/23786971/bc5c9b44-05aa-11e7-9480-21e121b9f4aa.png)

how should I fix it?

thanks for your patience.

**Comment by wuxudong** [comment]
Have you added BrigeUtils to your project? check you compile sources

**Comment by wuxudong** [comment]
I suggest you to follow example's instruction, run example first. then try it in your own project.  xcode settings are anoying.

**Comment by L-Jovi** [comment]
Am I right to copy physics folder reference to my project?

![image](https://cloud.githubusercontent.com/assets/7262199/23787879/0d063678-05af-11e7-9fb0-f0c85cd1ed09.png)

I'll check your example with mine, thanks again.

finally, awesome project :)

**Comment by wuxudong** [comment]
xcode has ·Add Files to  xxx  .   

just make sure all these files are in compile sources.

**Comment by L-Jovi** [comment]
@wuxudong  the difference is that you add by logic fold structure, not the blue color (physics folder structure)

close this issue, your example looks well, I'll try to convert my project from swift 2.3 to 3.0, looks painful but valuable.

![image](https://cloud.githubusercontent.com/assets/7262199/23790298/7b90d030-05b9-11e7-9968-918904f58a77.png)

**Comment by L-Jovi** [comment]
@wuxudong  feel sorry to trouble this issue again, I think actually __long press__ gesture is different from `onSelect`.

I cannot slide over values when I put chart component inside __scrollable__ component, like [react-native-scrollable-tab-view](https://github.com/skv-headless/react-native-scrollable-tab-view) or [react-native-swiper](https://github.com/leecade/react-native-swiper)

so like below image, user will be free to long press on chart, and delay could slide on chart rather than change whole parent component move.

![image](https://cloud.githubusercontent.com/assets/7262199/24135542/5491a7d6-0e45-11e7-8a67-b99bad42a1f6.png)

I notice mpandroid already support this feature [here](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/listener/OnChartGestureListener.java#L33) and also explained in [doc](https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart#gesture-callbacks).

but in iOS side, the behaviour maybe different, not ensure how to implements.

thanks for your time and patience.

regards.

**Comment by wuxudong** [comment]
-  Sometime horizontal scrollview inside swipe tabs  is confusing.  

and here is official suggested behavior [link](https://developer.android.com/design/patterns/swipe-views.html)

` If a view contains content that exceeds the width of the screen such as a wide email message, make sure the user's initial swipes will scroll horizontally within the view. Once the end of the content is reached, an additional swipe should navigate to the next view. In addition, support the use of edge swipes to immediately navigate between views when content scrolls horizontally`

and I made a sample,  three horizontal scrollable charts inside swipeable tabs( react-native-swiper). it behaves as expected. 
-   scrolls to the end. then an extra swipe will jump to next tab. 
-  or an edge swipe will navigate to next tab

long press , hold and delay will scroll inside chart, otherwise navigate to next tab, is not intuitive to me.


Export OnChartGestureListener to js is not difficult, but I don't think most people really need it.
the MotionEvent in api is too fundamental for react-native user.

Any further discussion is welcome.

**Comment by L-Jovi** [comment]
well, long press hold and delay will scroll inside chart is not intuitive, I admit your opinion,

under user's experience, swipe should move the whole tabView.

thanks for your time.
