### ISSUE TITLE
Utc string time on x Axis

### ISSUE THREAD

**Issue by NancyGarg** [wuxudong/react-native-charts-wrapper#726]
Need to show utc time on x axis(line chart).though its expecting double value.trying valueformatter,nothing is working

**Comment by wuxudong** [comment]
// formatting
  valueFormatter: PropTypes.oneOfType([
    PropTypes.oneOf(['largeValue', 'percent', 'date']),
    PropTypes.string,
    PropTypes.arrayOf(PropTypes.string)
  ]),

  // valueFormatterPattern, since, timeUnit are used when valueFormatter is 'date'
  // since: milliseconds of 2018-6-1, timeUnit: DAYS, x:9, valueFormatterPattern: YYYY-MM-dd
  // will display 2018-6-10

  // Note: for iOS/Charts, double is used for x, but in MpAndroidChart, float is used for x.
  // so in android, there will be precision loss when you use MILLISECONDS/SECOND/MINUTES as x value.   
  // you can use a different since like seconds of 2019 or use timeUnit DAYS, then x value will be within a valid range.

  valueFormatterPattern: PropTypes.string,
  since: PropTypes.number, // milliseconds from 1970-1-1 when x=0
  timeUnit: PropTypes.oneOf(['MILLISECONDS', 'SECONDS', 'MINUTES', 'HOURS', 'DAYS']), // timeUnit of x,
